name: Test
description: ASDsaddssadsda
title: "Title test"
labels: ["bug"]

body:
  - type: textarea
    id: approval
    validations:
      required: true
    attributes:
      label: sdasdadsadsadsa
      description: |
        adssdadsads
      value: |
        asddsadsasdads
  - type: markdown
    attributes:
      value: |
        [test](docs/wherever.md)

